const rows = [
['apple','사과','명사','음식','🍎','I eat an apple every morning.','나는 매일 아침 사과를 먹는다.'],
['bread','빵','명사','음식','🍞','We need some bread.','우리는 빵이 조금 필요하다.'],
['water','물','명사','음식','💧','Please drink enough water.','물을 충분히 마셔라.'],
['breakfast','아침 식사','명사','음식','🥣','Breakfast gives me energy.','아침 식사는 내게 힘을 준다.'],
['school','학교','명사','학교','🏫','I walk to school.','나는 학교에 걸어간다.'],
['student','학생','명사','학교','🧑‍🎓','Every student has a book.','모든 학생에게 책이 한 권 있다.'],
['teacher','선생님','명사','학교','👩‍🏫','My teacher is kind.','우리 선생님은 친절하다.'],
['homework','숙제','명사','학교','📝','I finished my homework.','나는 숙제를 끝냈다.'],
['library','도서관','명사','학교','📚','The library is quiet.','도서관은 조용하다.'],
['question','질문','명사','학교','❓','May I ask a question?','질문해도 될까요?'],
['family','가족','명사','생활','👨‍👩‍👧','My family eats together.','우리 가족은 함께 식사한다.'],
['friend','친구','명사','생활','🧑‍🤝‍🧑','She is my best friend.','그녀는 나의 가장 친한 친구다.'],
['morning','아침','명사','생활','🌅','I exercise in the morning.','나는 아침에 운동한다.'],
['weekend','주말','명사','생활','📅','What will you do this weekend?','이번 주말에 무엇을 할 거니?'],
['happy','행복한','형용사','감정','😊','I am happy to see you.','너를 만나서 기쁘다.'],
['worried','걱정하는','형용사','감정','😟','I am worried about the test.','나는 시험이 걱정된다.'],
['excited','신이 난','형용사','감정','🤩','We are excited about the trip.','우리는 여행에 신이 난다.'],
['kind','친절한','형용사','감정','💛','Be kind to others.','다른 사람에게 친절해라.'],
['run','달리다','동사','동작','🏃','I run in the park.','나는 공원에서 달린다.'],
['read','읽다','동사','동작','📖','I read before bed.','나는 자기 전에 읽는다.'],
['write','쓰다','동사','동작','✍️','Write your name here.','여기에 이름을 써라.'],
['listen','듣다','동사','동작','🎧','Listen to the question.','질문을 들어라.'],
['practice','연습하다','동사','동작','🎯','We practice speaking English.','우리는 영어 말하기를 연습한다.'],
['choose','고르다','동사','동작','☝️','Choose the best answer.','가장 알맞은 답을 골라라.'],
['computer','컴퓨터','명사','기술','💻','I use a computer for class.','나는 수업에 컴퓨터를 사용한다.'],
['internet','인터넷','명사','기술','🌐','The internet connects people.','인터넷은 사람들을 연결한다.'],
['program','프로그램','명사','기술','🧩','We made a simple program.','우리는 간단한 프로그램을 만들었다.'],
['robot','로봇','명사','기술','🤖','The robot can move.','그 로봇은 움직일 수 있다.'],
['nature','자연','명사','자연','🌿','We should protect nature.','우리는 자연을 보호해야 한다.'],
['weather','날씨','명사','자연','🌤️','The weather is nice today.','오늘 날씨가 좋다.'],
['mountain','산','명사','자연','⛰️','We climbed the mountain.','우리는 산에 올랐다.'],
['river','강','명사','자연','🏞️','The river is very long.','그 강은 매우 길다.'],
['travel','여행하다','동사','여행','🧳','I want to travel abroad.','나는 해외여행을 하고 싶다.'],
['station','역','명사','여행','🚉','Meet me at the station.','역에서 만나자.'],
['ticket','표','명사','여행','🎫','I bought a bus ticket.','나는 버스표를 샀다.'],
['map','지도','명사','여행','🗺️','Look at the map.','지도를 보아라.'],
['because','왜냐하면','접속사','핵심어','💡','I stayed home because it rained.','비가 와서 나는 집에 있었다.'],
['before','~전에','전치사','핵심어','⏮️','Wash your hands before dinner.','저녁 전에 손을 씻어라.'],
['different','다른','형용사','핵심어','🔀','We have different ideas.','우리는 서로 다른 생각을 갖고 있다.'],
['important','중요한','형용사','핵심어','❗','Sleep is important for students.','잠은 학생에게 중요하다.'],
['answer','대답','명사','학교','🙋','I know the answer.','나는 답을 알고 있다.'],
['classroom','교실','명사','학교','🪑','Our classroom is bright.','우리 교실은 밝다.'],
['delicious','맛있는','형용사','음식','😋','The soup is delicious.','그 수프는 맛있다.'],
['vegetable','채소','명사','음식','🥦','Vegetables are good for health.','채소는 건강에 좋다.'],
['remember','기억하다','동사','동작','🧠','Remember to bring your book.','책 가져오는 것을 기억해라.'],
['understand','이해하다','동사','동작','💭','I understand the question.','나는 그 질문을 이해한다.'],
['careful','조심하는','형용사','핵심어','⚠️','Be careful on the stairs.','계단에서 조심해라.'],
['future','미래','명사','핵심어','🚀','We learn for the future.','우리는 미래를 위해 배운다.'],
['beautiful','아름다운','형용사','자연','🌸','The flowers are beautiful.','그 꽃들은 아름답다.'],
['environment','환경','명사','자연','🌍','We must protect the environment.','우리는 환경을 보호해야 한다.']
];
window.WORDS = rows.map((v,i)=>({id:i+1,word:v[0],meaning:v[1],part:v[2],category:v[3],emoji:v[4],phonetic:'',examples:[{en:v[5],ko:v[6]},{en:`Can you use “${v[0]}” in a sentence?`,ko:`“${v[0]}”를 문장에 사용할 수 있나요?`}]}));
