const rows = [
['apple','사과','명사','음식','🍎','I eat an apple every morning.','나는 매일 아침 사과를 먹는다.'],
['bread','빵','명사','음식','🍞','We need some bread.','우리는 빵이 조금 필요하다.'],
['water','물','명사','음식','💧','Please drink enough water.','물을 충분히 마셔라.'],
['breakfast','아침 식사','명사','음식','🥣','Breakfast gives me energy.','아침 식사는 내게 힘을 준다.'],
['school','학교','명사','학교','🏫','I walk to school.','나는 학교에 걸어간다.'],
['student','학생','명사','학교','🧑‍🎓','Every student has a book.','모든 학생에게 책이 한 권 있다.'],
['teacher','선생님','명사','학교','👩‍🏫','My teacher is kind.','우리 선생님은 친절하다.'],
['homework','숙제','명사','학교','📝','I finished my homework.','나는 숙제를 끝냈다.'],
['library','도서관','명사','학교','📚','The library is quiet.','도서관은 조용하다.'],
['question','질문','명사','학교','❓','May I ask a question?','질문해도 될까요?'],
['family','가족','명사','생활','👨‍👩‍👧','My family eats together.','우리 가족은 함께 식사한다.'],
['friend','친구','명사','생활','🧑‍🤝‍🧑','She is my best friend.','그녀는 나의 가장 친한 친구다.'],
['morning','아침','명사','생활','🌅','I exercise in the morning.','나는 아침에 운동한다.'],
['weekend','주말','명사','생활','📅','What will you do this weekend?','이번 주말에 무엇을 할 거니?'],
['happy','행복한','형용사','감정','😊','I am happy to see you.','너를 만나서 기쁘다.'],
['worried','걱정하는','형용사','감정','😟','I am worried about the test.','나는 시험이 걱정된다.'],
['excited','신이 난','형용사','감정','🤩','We are excited about the trip.','우리는 여행에 신이 난다.'],
['kind','친절한','형용사','감정','💛','Be kind to others.','다른 사람에게 친절해라.'],
['run','달리다','동사','동작','🏃','I run in the park.','나는 공원에서 달린다.'],
['read','읽다','동사','동작','📖','I read before bed.','나는 자기 전에 읽는다.'],
['write','쓰다','동사','동작','✍️','Write your name here.','여기에 이름을 써라.'],
['listen','듣다','동사','동작','🎧','Listen to the question.','질문을 들어라.'],
['practice','연습하다','동사','동작','🎯','We practice speaking English.','우리는 영어 말하기를 연습한다.'],
['choose','고르다','동사','동작','☝️','Choose the best answer.','가장 알맞은 답을 골라라.'],
['computer','컴퓨터','명사','기술','💻','I use a computer for class.','나는 수업에 컴퓨터를 사용한다.'],
['internet','인터넷','명사','기술','🌐','The internet connects people.','인터넷은 사람들을 연결한다.'],
['program','프로그램','명사','기술','🧩','We made a simple program.','우리는 간단한 프로그램을 만들었다.'],
['robot','로봇','명사','기술','🤖','The robot can move.','그 로봇은 움직일 수 있다.'],
['nature','자연','명사','자연','🌿','We should protect nature.','우리는 자연을 보호해야 한다.'],
['weather','날씨','명사','자연','🌤️','The weather is nice today.','오늘 날씨가 좋다.'],
['mountain','산','명사','자연','⛰️','We climbed the mountain.','우리는 산에 올랐다.'],
['river','강','명사','자연','🏞️','The river is very long.','그 강은 매우 길다.'],
['travel','여행하다','동사','여행','🧳','I want to travel abroad.','나는 해외여행을 하고 싶다.'],
['station','역','명사','여행','🚉','Meet me at the station.','역에서 만나자.'],
['ticket','표','명사','여행','🎫','I bought a bus ticket.','나는 버스표를 샀다.'],
['map','지도','명사','여행','🗺️','Look at the map.','지도를 보아라.'],
['because','왜냐하면','접속사','핵심어','💡','I stayed home because it rained.','비가 와서 나는 집에 있었다.'],
['before','~전에','전치사','핵심어','⏮️','Wash your hands before dinner.','저녁 전에 손을 씻어라.'],
['different','다른','형용사','핵심어','🔀','We have different ideas.','우리는 서로 다른 생각을 갖고 있다.'],
['important','중요한','형용사','핵심어','❗','Sleep is important for students.','잠은 학생에게 중요하다.'],
['answer','대답','명사','학교','🙋','I know the answer.','나는 답을 알고 있다.'],
['classroom','교실','명사','학교','🪑','Our classroom is bright.','우리 교실은 밝다.'],
['delicious','맛있는','형용사','음식','😋','The soup is delicious.','그 수프는 맛있다.'],
['vegetable','채소','명사','음식','🥦','Vegetables are good for health.','채소는 건강에 좋다.'],
['remember','기억하다','동사','동작','🧠','Remember to bring your book.','책 가져오는 것을 기억해라.'],
['understand','이해하다','동사','동작','💭','I understand the question.','나는 그 질문을 이해한다.'],
['careful','조심하는','형용사','핵심어','⚠️','Be careful on the stairs.','계단에서 조심해라.'],
['future','미래','명사','핵심어','🚀','We learn for the future.','우리는 미래를 위해 배운다.'],
['beautiful','아름다운','형용사','자연','🌸','The flowers are beautiful.','그 꽃들은 아름답다.'],
['environment','환경','명사','자연','🌍','We must protect the environment.','우리는 환경을 보호해야 한다.'],
['exam','시험','명사','학교','📋','I studied hard for the exam.','나는 시험을 위해 열심히 공부했다.'],
['lesson','수업','명사','학교','📘','Today’s lesson was interesting.','오늘 수업은 재미있었다.'],
['notebook','공책','명사','학교','📓','Write the answer in your notebook.','공책에 답을 쓰세요.'],
['pencil','연필','명사','학교','✏️','May I borrow your pencil?','네 연필을 빌려도 될까?'],
['subject','과목','명사','학교','📚','English is my favorite subject.','영어는 내가 가장 좋아하는 과목이다.'],
['science','과학','명사','학교','🔬','We did an experiment in science class.','우리는 과학 시간에 실험을 했다.'],
['math','수학','명사','학교','➗','This math problem is easy.','이 수학 문제는 쉽다.'],
['history','역사','명사','학교','🏛️','We learn about the past in history.','우리는 역사에서 과거를 배운다.'],
['language','언어','명사','학교','💬','English is a global language.','영어는 세계적인 언어이다.'],
['grade','성적','명사','학교','💯','She got a good grade.','그녀는 좋은 성적을 받았다.'],
['study','공부하다','동사','학교','🧑‍💻','I study English after dinner.','나는 저녁 식사 후에 영어를 공부한다.'],
['learn','배우다','동사','학교','🌱','We learn something new every day.','우리는 매일 새로운 것을 배운다.'],
['teach','가르치다','동사','학교','👨‍🏫','They teach children how to read.','그들은 아이들에게 읽는 법을 가르친다.'],
['explain','설명하다','동사','학교','🗣️','Please explain the answer.','답을 설명해 주세요.'],
['solve','풀다','동사','학교','🧩','Can you solve this problem?','이 문제를 풀 수 있니?'],
['house','집','명사','생활','🏠','Their house has a small garden.','그들의 집에는 작은 정원이 있다.'],
['room','방','명사','생활','🛏️','My room is clean and bright.','내 방은 깨끗하고 밝다.'],
['door','문','명사','생활','🚪','Please close the door.','문을 닫아 주세요.'],
['window','창문','명사','생활','🪟','Open the window for fresh air.','신선한 공기가 들어오도록 창문을 여세요.'],
['kitchen','부엌','명사','생활','🍳','My father is cooking in the kitchen.','아버지는 부엌에서 요리하고 있다.'],
['bed','침대','명사','생활','🛌','I went to bed early.','나는 일찍 잠자리에 들었다.'],
['clothes','옷','명사','생활','👕','These clothes are comfortable.','이 옷들은 편안하다.'],
['shoes','신발','명사','생활','👟','Take off your shoes here.','여기에서 신발을 벗으세요.'],
['money','돈','명사','생활','💰','I saved money for a new bike.','나는 새 자전거를 사려고 돈을 모았다.'],
['time','시간','명사','생활','⏰','We do not have much time.','우리에게 시간이 많지 않다.'],
['day','하루','명사','생활','☀️','It was a wonderful day.','멋진 하루였다.'],
['night','밤','명사','생활','🌙','The stars shine at night.','별들은 밤에 빛난다.'],
['today','오늘','부사','생활','📆','I feel much better today.','나는 오늘 훨씬 나아졌다.'],
['tomorrow','내일','부사','생활','➡️','We will meet again tomorrow.','우리는 내일 다시 만날 것이다.'],
['yesterday','어제','부사','생활','⬅️','It rained a lot yesterday.','어제 비가 많이 왔다.'],
['mother','어머니','명사','사람','👩','My mother makes delicious soup.','우리 어머니는 맛있는 수프를 만든다.'],
['father','아버지','명사','사람','👨','My father drives to work.','우리 아버지는 차를 타고 출근한다.'],
['brother','형제','명사','사람','👦','My brother likes basketball.','내 형제는 농구를 좋아한다.'],
['sister','자매','명사','사람','👧','My sister plays the piano.','내 자매는 피아노를 친다.'],
['parent','부모','명사','사람','🧑','A parent came to the school.','한 학부모가 학교에 왔다.'],
['child','아이','명사','사람','🧒','The child is drawing a picture.','그 아이는 그림을 그리고 있다.'],
['people','사람들','명사','사람','👥','Many people use smartphones.','많은 사람이 스마트폰을 사용한다.'],
['person','사람','명사','사람','🧍','She is a very kind person.','그녀는 매우 친절한 사람이다.'],
['neighbor','이웃','명사','사람','🏘️','Our neighbor has a friendly dog.','우리 이웃에게는 친근한 개가 있다.'],
['team','팀','명사','사람','🤝','Our team won the game.','우리 팀이 경기에서 이겼다.'],
['member','구성원','명사','사람','🙋','Every member has a role.','모든 구성원에게 역할이 있다.'],
['rice','쌀·밥','명사','음식','🍚','We usually eat rice for dinner.','우리는 보통 저녁으로 밥을 먹는다.'],
['milk','우유','명사','음식','🥛','I drink a glass of milk.','나는 우유 한 잔을 마신다.'],
['fruit','과일','명사','음식','🍊','Fresh fruit is good for you.','신선한 과일은 건강에 좋다.'],
['meat','고기','명사','음식','🥩','We cooked the meat carefully.','우리는 고기를 조심스럽게 요리했다.'],
['fish','생선·물고기','명사','음식','🐟','This fish lives in clean water.','이 물고기는 깨끗한 물에서 산다.'],
['egg','달걀','명사','음식','🥚','She had an egg for breakfast.','그녀는 아침으로 달걀을 먹었다.'],
['lunch','점심','명사','음식','🍱','Let us eat lunch together.','함께 점심을 먹자.'],
['dinner','저녁 식사','명사','음식','🍽️','Dinner will be ready soon.','저녁 식사가 곧 준비될 것이다.'],
['hungry','배고픈','형용사','음식','🤤','I am hungry after exercise.','나는 운동 후에 배가 고프다.'],
['thirsty','목마른','형용사','음식','🥤','The runner was very thirsty.','그 달리기 선수는 매우 목이 말랐다.'],
['cook','요리하다','동사','음식','👩‍🍳','I can cook a simple meal.','나는 간단한 식사를 요리할 수 있다.'],
['taste','맛보다','동사','음식','👅','Taste the soup before serving it.','수프를 내기 전에 맛보세요.'],
['sad','슬픈','형용사','감정','😢','The movie made me sad.','그 영화는 나를 슬프게 했다.'],
['angry','화난','형용사','감정','😠','He was angry about the mistake.','그는 그 실수 때문에 화가 났다.'],
['tired','피곤한','형용사','감정','🥱','I felt tired after practice.','나는 연습 후에 피곤했다.'],
['afraid','두려워하는','형용사','감정','😨','Do not be afraid of mistakes.','실수를 두려워하지 마라.'],
['proud','자랑스러운','형용사','감정','🥇','I am proud of my team.','나는 우리 팀이 자랑스럽다.'],
['surprised','놀란','형용사','감정','😲','We were surprised by the news.','우리는 그 소식에 놀랐다.'],
['interesting','재미있는','형용사','감정','✨','This book is very interesting.','이 책은 매우 재미있다.'],
['boring','지루한','형용사','감정','😐','The long wait was boring.','긴 기다림은 지루했다.'],
['easy','쉬운','형용사','핵심어','👌','The first question was easy.','첫 번째 문제는 쉬웠다.'],
['difficult','어려운','형용사','핵심어','🧗','This puzzle looks difficult.','이 퍼즐은 어려워 보인다.'],
['strong','강한','형용사','핵심어','💪','The wind is very strong today.','오늘 바람이 매우 강하다.'],
['weak','약한','형용사','핵심어','🔋','The signal is weak here.','여기는 신호가 약하다.'],
['walk','걷다','동사','동작','🚶','We walk to school together.','우리는 함께 학교에 걸어간다.'],
['jump','뛰어오르다','동사','동작','🤸','The cat can jump high.','그 고양이는 높이 뛸 수 있다.'],
['sit','앉다','동사','동작','🪑','Please sit next to me.','내 옆에 앉아 주세요.'],
['stand','서다','동사','동작','🧍','We stand in a line.','우리는 줄을 서 있다.'],
['open','열다','동사','동작','📂','Open your book to page ten.','책 10쪽을 펴세요.'],
['close','닫다','동사','동작','📕','Close the window before leaving.','떠나기 전에 창문을 닫으세요.'],
['bring','가져오다','동사','동작','🎒','Bring your notebook tomorrow.','내일 공책을 가져오세요.'],
['buy','사다','동사','동작','🛒','I need to buy a new pen.','나는 새 펜을 사야 한다.'],
['sell','팔다','동사','동작','🏷️','They sell fruit at the market.','그들은 시장에서 과일을 판다.'],
['help','돕다','동사','동작','🫶','Can you help me with this box?','이 상자 옮기는 것을 도와줄래?'],
['make','만들다','동사','동작','🛠️','We made a model airplane.','우리는 모형 비행기를 만들었다.'],
['use','사용하다','동사','동작','🔧','Use this key to open the door.','이 열쇠로 문을 여세요.'],
['find','찾다','동사','동작','🔎','I cannot find my phone.','나는 내 휴대전화를 찾을 수 없다.'],
['give','주다','동사','동작','🎁','Please give me some water.','물 좀 주세요.'],
['take','가져가다','동사','동작','🤲','Take an umbrella with you.','우산을 가져가세요.'],
['show','보여주다','동사','동작','🖼️','Show me your new drawing.','네 새 그림을 보여 줘.'],
['ask','묻다','동사','동작','🙋','You can ask the teacher.','선생님께 물어볼 수 있다.'],
['tell','말하다','동사','동작','📢','Tell me the truth.','내게 진실을 말해 줘.'],
['speak','말하다','동사','동작','🗨️','Please speak slowly.','천천히 말해 주세요.'],
['watch','보다','동사','동작','👀','We watched a science video.','우리는 과학 영상을 보았다.'],
['play','놀다·경기하다','동사','동작','⚽','They play soccer after school.','그들은 방과 후에 축구를 한다.'],
['work','일하다','동사','동작','💼','My parents work in the city.','우리 부모님은 도시에서 일하신다.'],
['start','시작하다','동사','동작','▶️','The class starts at nine.','수업은 9시에 시작한다.'],
['finish','끝내다','동사','동작','🏁','Finish your homework first.','숙제를 먼저 끝내라.'],
['wait','기다리다','동사','동작','⌛','Wait for me at the bus stop.','버스 정류장에서 나를 기다려 줘.'],
['meet','만나다','동사','동작','🤝','I will meet my friend tomorrow.','나는 내일 친구를 만날 것이다.'],
['live','살다','동사','동작','🏡','We live near the school.','우리는 학교 근처에 산다.'],
['move','움직이다','동사','동작','↔️','The robot can move its arms.','그 로봇은 팔을 움직일 수 있다.'],
['sun','태양','명사','자연','☀️','The sun rises in the east.','태양은 동쪽에서 뜬다.'],
['moon','달','명사','자연','🌕','The moon looks bright tonight.','오늘 밤 달이 밝아 보인다.'],
['star','별','명사','자연','⭐','We saw many stars in the sky.','우리는 하늘에서 많은 별을 보았다.'],
['sky','하늘','명사','자연','🌌','The sky turned orange.','하늘이 주황색으로 변했다.'],
['cloud','구름','명사','자연','☁️','A dark cloud covered the sun.','어두운 구름이 태양을 가렸다.'],
['rain','비','명사','자연','🌧️','The rain stopped in the afternoon.','비는 오후에 그쳤다.'],
['snow','눈','명사','자연','❄️','The children played in the snow.','아이들은 눈 속에서 놀았다.'],
['wind','바람','명사','자연','💨','The wind moved the leaves.','바람이 나뭇잎을 움직였다.'],
['tree','나무','명사','자연','🌳','That tree is over one hundred years old.','저 나무는 100년이 넘었다.'],
['flower','꽃','명사','자연','🌼','A yellow flower grew by the road.','길가에 노란 꽃이 피었다.'],
['animal','동물','명사','자연','🐾','Every animal needs clean water.','모든 동물에게 깨끗한 물이 필요하다.'],
['bird','새','명사','자연','🐦','A small bird sat on the roof.','작은 새 한 마리가 지붕에 앉았다.'],
['dog','개','명사','자연','🐕','The dog followed me home.','그 개는 집까지 나를 따라왔다.'],
['cat','고양이','명사','자연','🐈','Our cat sleeps by the window.','우리 고양이는 창가에서 잔다.'],
['sea','바다','명사','자연','🌊','The sea was calm this morning.','오늘 아침 바다는 잔잔했다.'],
['lake','호수','명사','자연','🏞️','We walked around the lake.','우리는 호수 주변을 걸었다.'],
['bus','버스','명사','여행','🚌','I take the bus to school.','나는 버스를 타고 학교에 간다.'],
['train','기차','명사','여행','🚆','The train arrived on time.','기차는 제시간에 도착했다.'],
['car','자동차','명사','여행','🚗','Their car is parked outside.','그들의 차는 밖에 주차되어 있다.'],
['bicycle','자전거','명사','여행','🚲','She rides her bicycle to the park.','그녀는 자전거를 타고 공원에 간다.'],
['airplane','비행기','명사','여행','✈️','The airplane flew above the clouds.','비행기는 구름 위를 날았다.'],
['airport','공항','명사','여행','🛫','We arrived at the airport early.','우리는 공항에 일찍 도착했다.'],
['road','도로','명사','여행','🛣️','This road leads to the beach.','이 길은 해변으로 이어진다.'],
['street','거리','명사','여행','🚦','Be careful when crossing the street.','길을 건널 때 조심하세요.'],
['country','나라','명사','여행','🌏','I want to visit another country.','나는 다른 나라를 방문하고 싶다.'],
['city','도시','명사','여행','🏙️','Seoul is a busy city.','서울은 분주한 도시이다.'],
['town','마을','명사','여행','🏘️','The town has a small museum.','그 마을에는 작은 박물관이 있다.'],
['place','장소','명사','여행','📍','This is a good place to rest.','이곳은 쉬기 좋은 장소이다.'],
['left','왼쪽','명사','여행','⬅️','Turn left at the corner.','모퉁이에서 왼쪽으로 도세요.'],
['right','오른쪽','명사','여행','➡️','The library is on your right.','도서관은 오른쪽에 있다.'],
['straight','똑바로','부사','여행','⬆️','Go straight for two blocks.','두 블록 동안 똑바로 가세요.'],
['phone','전화기','명사','기술','📱','My phone needs charging.','내 휴대전화는 충전이 필요하다.'],
['screen','화면','명사','기술','🖥️','The answer appears on the screen.','답이 화면에 나타난다.'],
['keyboard','키보드','명사','기술','⌨️','Use the keyboard to type your name.','키보드로 이름을 입력하세요.'],
['mouse','마우스','명사','기술','🖱️','Click the button with the mouse.','마우스로 버튼을 클릭하세요.'],
['code','코드','명사','기술','👨‍💻','This code makes the character move.','이 코드는 캐릭터를 움직이게 한다.'],
['data','데이터','명사','기술','📊','The computer saves the data.','컴퓨터가 데이터를 저장한다.'],
['game','게임','명사','기술','🎮','We designed a simple game.','우리는 간단한 게임을 설계했다.'],
['website','웹사이트','명사','기술','🌐','Our class made a website.','우리 반은 웹사이트를 만들었다.'],
['online','온라인으로','부사','기술','📡','We studied online today.','우리는 오늘 온라인으로 공부했다.'],
['message','메시지','명사','기술','💬','I sent a message to my friend.','나는 친구에게 메시지를 보냈다.'],
['camera','카메라','명사','기술','📷','This camera takes clear pictures.','이 카메라는 선명한 사진을 찍는다.'],
['video','영상','명사','기술','🎬','We watched an English video.','우리는 영어 영상을 보았다.'],
['always','항상','부사','핵심어','♾️','She always arrives on time.','그녀는 항상 제시간에 도착한다.'],
['usually','보통','부사','핵심어','🔄','I usually walk to school.','나는 보통 학교에 걸어간다.'],
['sometimes','가끔','부사','핵심어','🎲','We sometimes eat outside.','우리는 가끔 외식을 한다.'],
['never','결코 ~않다','부사','핵심어','🚫','I never forget my homework.','나는 숙제를 절대 잊지 않는다.'],
['often','자주','부사','핵심어','🔁','He often reads after dinner.','그는 저녁 식사 후에 자주 책을 읽는다.'],
['again','다시','부사','핵심어','↩️','Please say that again.','다시 말해 주세요.'],
['together','함께','부사','핵심어','🫂','Let us solve the problem together.','그 문제를 함께 풀자.'],
['alone','혼자','부사','핵심어','🧍','She finished the work alone.','그녀는 혼자 그 일을 끝냈다.'],
['many','많은','형용사','핵심어','➕','Many students joined the club.','많은 학생이 동아리에 가입했다.'],
['few','거의 없는·소수의','형용사','핵심어','🤏','Few people knew the answer.','답을 아는 사람은 거의 없었다.'],
['some','약간의·몇몇의','형용사','핵심어','🔢','I need some help.','나는 도움이 조금 필요하다.'],
['every','모든','형용사','핵심어','✅','I practice English every day.','나는 매일 영어를 연습한다.'],
['first','첫 번째의','형용사','핵심어','1️⃣','She won first place.','그녀는 1등을 했다.'],
['last','마지막의','형용사','핵심어','🔚','This is the last question.','이것이 마지막 문제이다.']
];
window.WORDS = rows.map((v,i)=>({id:i+1,word:v[0],meaning:v[1],part:v[2],category:v[3],emoji:v[4],phonetic:'',examples:[{en:v[5],ko:v[6]},{en:`Please remember the word “${v[0]}.”`,ko:`“${v[0]}”라는 단어를 기억하세요.`},{en:`How do you spell “${v[0]}”?`,ko:`“${v[0]}”의 철자는 어떻게 쓰나요?`}]}));
